apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    traefik.ingress.kubernetes.io/service-weights: |
      laxuanlinhwebsocketchat: 80%
      service-#{Build.BuildId}#-green: 20%
  name: websocket-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: laxuanlinhwebsocketchat
          servicePort: 8080
        path: /websocket
      - backend:
          serviceName: service-#{Build.BuildId}#-green
          servicePort: 8080
        path: /websocket
