apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: websocket-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: laxuanlinhwebsocketchat
          servicePort: 80
        path: /websocket
      - backend:
          serviceName: service-#{Build.BuildId}#-green
          servicePort: 80
        path: /websocket