apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: websocket-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  name: websocket-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: laxuanlinhwebsocketchat
          servicePort: 8080
        path: /websocket
