apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websocket-ingress
	annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: laxuanlinhwebsocketchat
          servicePort: 80
        path: /
